[project]
name = "termometermonitor"
version = "0.1.0"
description = "Store metrics from BLE devices"
authors = ["lexsys.ko <lexsys.ko@gmail.com>"]
license = "MIT"
readme = "README.md"

requires-python = ">=3.13"
dependencies = [
    "bleak>=3.0.2",
]

[tool.black]
line-length = 120

[tool.ruff]
line-length = 120

[tool.ruff.lint]
select = ["E4", "E7", "E9"]
ignore = [
    #    "RUF012",
    #    "RUF022",
    #    "RUF100",
    #    "S112",
    #    "SIM118",
    #    "UP031",
    #    "UP032",
    #    "BLE001",
    #    "PLW1508"
]

[tool.isort]
profile = "black"
line_length = 120

[tool.flake8]
max-line-length = 120



[tool.uv]
exclude-newer = "7 days"
exclude-newer-package = { some-urgent-package = false }
