[project]
name = "ThermometerMonitor"
version = "0.2.2"
description = "Asynchronous BLE environmental monitor and telemetry logger for smart thermometers."
authors = [{ name = "lexsys.ko", email = "lexsys.ko@gmail.com" }]

license = { text = "MIT" }
readme = "README.md"

requires-python = ">=3.12"
dependencies = [
    "aioblescan>=0.2.14; sys_platform == 'linux'",
    "bleak>=3.0.2",
    "python-dotenv>=1.2.3",
]
classifiers = [
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
]
keywords = ["python", "http", "bluetooth", "monitoring", "BLE passive mode"]

[project.urls]
Homepage = "https://github.com/lexsysko/ThermometerMonitor"
Documentation = "https://github.com/lexsysko/ThermometerMonitor#readme"
Repository = "https://github.com/lexsysko/ThermometerMonitor.git"
Issues = "https://github.com/lexsysko/ThermometerMonitor/issues"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src/ThermometerMonitor"]

[project.scripts]
thermometermonitor = "ThermometerMonitor.main:run"

[tool.hatch.build.sdist]
relative-install = true

[tool.black]
line-length = 120

[tool.ruff]
line-length = 120

[tool.ruff.lint]
select = ["E4", "E7", "E9"]
ignore = [
    #    "RUF012",
    #    "RUF022",
    #    "RUF100",
    #    "S112",
    #    "SIM118",
    #    "UP031",
    #    "UP032",
    #    "BLE001",
    #    "PLW1508"
]

[tool.isort]
profile = "black"
line_length = 120

[tool.flake8]
max-line-length = 120



[tool.uv]
exclude-newer = "7 days"
exclude-newer-package = { some-urgent-package = false }
